version: "3.7"
services:
  geocoding:
    environment:
      ENABLE_FAKE_GEOCODER: "True"
  curator:
    environment:
      GOOGLE_OAUTH_CLIENT_ID: "foo"
      GOOGLE_OAUTH_CLIENT_SECRET: "bar"
      MAPBOX_TOKEN: ""
