name: Export prod case data

on:
  push:
    # Update the data when the export script changes.
    branches: [main]
    paths:
      - "data-serving/scripts/export-data/**"
  schedule:
    # Every day at 6AM UTC (data is typically ingested at 5AM UTC).
    - cron: "0 6 * * *"

jobs:
  export-case-data-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Install MongoDB CLIs
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5DC22404A6F9F1CA 656408E390CFB1F5
          sudo dpkg --purge mongodb-org-database-tools-extra
          sudo apt-get update
          sudo apt-get install -f -y --allow-downgrades mongodb-org=4.2.6 mongodb-org-server=4.2.6 mongodb-org-shell=4.2.6 mongodb-org-mongos=4.2.6 mongodb-org-tools=4.2.6 libcurl3

      - name: Create gzip of CSV and JSON prod case data
        run: |
          ./data-serving/scripts/export-data/export_data.sh -m "${{ secrets.DB_CONNECTION_URL_PROD }}"
          ./data-serving/scripts/export-data/export_data.sh -m "${{ secrets.DB_CONNECTION_URL_PROD }}" -o json
          tar -cvzf data/cases.tar.gz cases.csv cases.json

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/cases.tar.gz
          git commit -m "Automatic export of case data"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.EXPORT_DATA_ACCESS_TOKEN }}
          branch: main
