# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Curator UI Node.js CI

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/curator-ui-node.yml"
      - "verification/curator-service/ui/**"
  pull_request:
    branches: [master]
    paths:
      - ".github/workflows/curator-ui-node.yml"
      - "verification/curator-service/ui/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Build and test
        run: |
          npm ci
          npm run build
          npm test
        working-directory: verification/curator-service/ui
        env:
          CI: true
      - name: Cypress integration tests
        run: npm run cypress-ci-test
        working-directory: verification/curator-service/ui
        timeout-minutes: 15
        env:
          CI: true
