name: Update database schemas

on:
  push:
    # Run workflow when the schema changes.
    branches: [main]
    paths:
      - "data-serving/data-service/schemas/**"

jobs:
  update-case-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Update prod schema
        env:
          CONN: ${{ secrets.DB_CONNECTION_URL_PROD }}
          DB: "covid19"
          COLL: "cases"
          # Those are relative to the setup-db directory, not the working dir.
          SCHEMA: "../../data-service/schemas/cases.schema.json"
          INDEXES: "../../data-service/schemas/cases.indexes.json"
        run: npm --prefix data-serving/scripts/setup-db run setup
      - name: Update dev schema
        env:
          CONN: ${{ secrets.DB_CONNECTION_URL_DEV }}
          DB: "covid19"
          COLL: "cases"
          # Those are relative to the setup-db directory, not the working dir.
          SCHEMA: "../../data-service/schemas/cases.schema.json"
          INDEXES: "../../data-service/schemas/cases.indexes.json"
        run: npm --prefix data-serving/scripts/setup-db run setup